apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificate-issuer-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ibm-common-services
    server: https://kubernetes.default.svc
  project: cloudpak
  source:
    path: cloudpak/certificate
    repoURL: https://github.com/jtarte/rhacm-rhgitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true