apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  queueManager:
    name: QM1
    availability:
      type: NativeHA
    mqsc:
    - configMap:
        name: mq-configmap
        items:
        - qm1.mqsc
    storage:
      defaultClass: ibmc-vpc-block-10iops-tier
      queueManager:
        type: persistent-claim
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.2.4.0-r1
  web:
    enabled: false
  pki:
    keys:
      - name: default
        secret:
          secretName: mq-mvp-instance-tls
          items: 
          - tls.key
          - tls.crt
          - ca.crt 
          