kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-project-clusterrole
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets