apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mq-instance
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cp4i-mq-project
    server: https://kubernetes.default.svc
  project: cp4i
  source:
    path: mq/instance
    repoURL: https://github.com/jtarte/rhacm-rhgitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true