apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: apic-operator-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: apic-operator
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: ibm-apiconnect
                  namespace: openshift-operators
                  labels:
                    operators.coreos.com/ibm-apiconnect.openshift-operators: ''
                spec:
                  channel: v2.4
                  installPlanApproval: Automatic
                  name: ibm-apiconnect
                  source: ibm-operator-catalog
                  sourceNamespace: openshift-marketplace