apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: cp4i-operator-policy-placement-binding
placementRef:
  name: cp4i-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: cpfs-operator-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: mq-operator-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: apic-operator-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io