apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cpfs-operator-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cpfs-operator
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: ibm-common-service-operator
                  namespace: openshift-operators
                spec:
                  channel: v3
                  installPlanApproval: Automatic
                  name: ibm-common-service-operator
                  source: ibm-operator-catalog
                  sourceNamespace: openshift-marketplace