apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: entitlement-key-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: entitlment-key
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - cp4i-*
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                   name: ibm-entitlement-key
                data:
                  .dockerconfigjson: >-           
                    < put here your base64 encoded docker login information>
                type: kubernetes.io/dockerconfigjson
