apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ibm-catalog-config-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ibm-catalogsource
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: ibm-operator-catalog
                  namespace: openshift-marketplace
                spec:
                  displayName: IBM Operator Catalog
                  image: 'icr.io/cpopen/ibm-operator-catalog:latest'
                  publisher: IBM
                  sourceType: grpc
                  updateStrategy:
                    registryPoll:
                      interval: 45m