kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: checker-apic-binding
  namespace: cp4i-apic-project
  annotations:
    argocd.argoproj.io/sync-wave: "10"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin