apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhgitops/application/certificate-issuer
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: mq-instance
    app.kubernetes.io/part-of: cp4i
    apps.open-cluster-management.io/reconcile-rate: medium
  name: certificate-issuer
spec:
  channel: cp4i-dep/githubcom-jtarte-rhacm-rhgitops
  overrides:
    - clusterName: /
      clusterOverrides:
        - path: metadata.namespace
          value: openshift-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: cp4i-placement
  secondaryChannel: ''